server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_order
    username: ecommerce
    password: ecommerce
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
      paymentService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
  retry:
    instances:
      inventoryService:
        max-attempts: 3
        wait-duration: 500ms
      paymentService:
        max-attempts: 3
        wait-duration: 500ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
